version: "3"

vars:
  BUN_VERSION: "1.0.27"
  OUTFILE: "./dist/setup"

tasks:
  install:
    desc: Install dependencies for the project
    cmds:
      - task: install:bun
      - task: install:project

  build:
    deps:
      - install
    desc: Build the project
    generates:
      - "{{.OUTFILE}}"
    cmds:
      - bun build ./setup.ts --compile --outfile {{.OUTFILE}}

  run:
    deps:
      - build
    desc: Run the project
    cmds:
      - "{{.OUTFILE}}"

  update:
    desc: Updates system packages from Brewfile
    generates:
      - Brewfile.lock.json
    cmds:
      - brew bundle install

  dump:
    desc: Writes system packages to Brewfile
    cmds:
      - brew bundle dump --force

  install:bun:
    internal: true
    silent: true
    desc: Install Bun
    cmds:
      - curl -fsSL https://bun.sh/install | bash -s "bun-v{{.BUN_VERSION}}"
    status:
      - bun -v | grep "{{.BUN_VERSION}}"

  install:project:
    internal: true
    silent: true
    desc: Install project dependencies
    cmds:
      - bun install
    sources:
      - package.json
      - bun.lockb
