name: Build and Test

on:
  - push
  - pull_request

jobs:
  build:

    runs-on: [ubuntu-latest, macos-latest]

    steps:
    - uses: actions/checkout@master
    - name: Lint Script
      run: shellcheck -x *.sh
    - name: Run Script
      run: bash setup.sh
