name: Main Workflow

on:
  - push
  - pull_request

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
    - uses: actions/checkout@master
    - name: Lint Script
      if: matrix.os == 'ubuntu-latest'
      uses: ludeeus/action-shellcheck@0.1.0
    - name: Run Script
      run: bash setup.sh
      env:
        NO_INSTALL: true
        NO_INTERACTIVE: true
