name: Test Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  HOMEBREW_NO_INSTALL_UPGRADE: 1
  HOMEBREW_NO_INSTALL_CLEANUP: 1
  HOMEBREW_NO_AUTO_UPDATE: 1
  HOMEBREW_GITHUB_PACKAGES_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  PROFILE: ~/Documents/PowerShell/Microsoft.PowerShell_profile.ps1

jobs:
  build:
    name: Test Setup

    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3

    - name: Prepare Windows Environment
      if: runner.os == 'Windows'
      shell: powershell
      run: echo $null >> ${{ env.PROFILE }}

    - name: Setup Node.js 16
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: yarn

    - name: Run setup
      run: yarn --frozen-lockfile --prefer-offline
